use aetheris_core::{MAX_INPUTS, MAX_OUTPUTS};
use halo2_proofs::{
    arithmetic::Field,
    circuit::{Layouter, SimpleFloorPlanner, Value},
    plonk::{
        Advice, Circuit, Column, ConstraintSystem, ErrorFront, Expression, Instance, Selector,
        create_proof, keygen_pk, keygen_vk,
    },
    poly::{
        Rotation,
        kzg::{
            commitment::{KZGCommitmentScheme, ParamsKZG},
            multiopen::{ProverSHPLONK, VerifierSHPLONK},
            strategy::SingleStrategy,
        },
    },
    transcript::{
        Blake2bWrite, Blake2bRead, Challenge255, TranscriptReadBuffer, TranscriptWriterBuffer,
    },
};
use halo2_proofs::plonk::verify_proof_multi as verify_proof;
use halo2_proofs::poly::commitment::Params;
use halo2curves::bn256::{Fr, Bn256, G1Affine};
use std::sync::OnceLock;
use std::fs;
use rand_chacha::ChaCha20Rng;
use rand_chacha::rand_core::SeedableRng;
use rand::rngs::OsRng as CryptoRng;
use rand::RngCore;
use aes_gcm::{Aes256Gcm, Key, Nonce, KeyInit, AeadCore, aead::Aead};
use x25519_dalek::{EphemeralSecret, PublicKey, StaticSecret};


const PROVING_K: u32 = 11;

// Cached CRS and proving key — generated once, shared across prover & verifier.
static CACHED_PARAMS: OnceLock<ParamsKZG<Bn256>> = OnceLock::new();
static CACHED_VK: OnceLock<halo2_proofs::plonk::VerifyingKey<G1Affine>> = OnceLock::new();
static CACHED_PK: OnceLock<halo2_proofs::plonk::ProvingKey<G1Affine>> = OnceLock::new();

fn ensure_params() -> &'static ParamsKZG<Bn256> {
    CACHED_PARAMS.get_or_init(|| {
        // Try loading canonical CRS from file (generated by gen_crs tool with random.org seed)
        let crs_paths = ["aetheris-zkp/crs.bin", "crs.bin"];
        for path in &crs_paths {
            if let Ok(data) = fs::read(path) {
                let mut cursor = std::io::Cursor::new(&data);
                if let Ok(params) = ParamsKZG::<Bn256>::read(&mut cursor) {
                    eprintln!("[ZK] Loaded CRS from {} (k={})", path, params.k());
                    return params;
                }
            }
        }
        // Fallback: deterministic seed for development/testing only
        eprintln!("[ZK] WARNING: No crs.bin found. Using deterministic seed (DEV ONLY — proofs are forgeable!)");
        let seed = *b"Aetheris ZK CRS deterministic v1";
        ParamsKZG::<Bn256>::setup(PROVING_K, &mut ChaCha20Rng::from_seed(seed))
    })
}

fn ensure_keys() -> (&'static halo2_proofs::plonk::VerifyingKey<G1Affine>,
                     &'static halo2_proofs::plonk::ProvingKey<G1Affine>) {
    let params = ensure_params();
    let vk = CACHED_VK.get_or_init(|| {
        let dummy = ValueConservationCircuit::dummy();
        keygen_vk(params, &dummy).expect("keygen_vk failed")
    });
    let pk = CACHED_PK.get_or_init(|| {
        let dummy = ValueConservationCircuit::dummy();
        keygen_pk(params, vk.clone(), &dummy).expect("keygen_pk failed")
    });
    (vk, pk)
}

/// Simple circuit-friendly commitment: amount + blinding (in Fr field)
/// Hashes blinding bytes; if hash >= Fr MODULUS, reduces by masking top bit.
pub fn create_commitment(amount: u64, blinding: &[u8; 32]) -> [u8; 32] {
    let amt_fr = Fr::from(amount);
    let h = blake3::hash(blinding);
    let mut bytes = *h.as_bytes();
    // Fr MODULUS = 0x30644e... — clear top 2 bits to guarantee < modulus
    bytes[31] &= 0x2F;
    let blind_fr = Fr::from_bytes(&bytes).expect("masked bytes always valid Fr");
    let commitment_fr = amt_fr + blind_fr;
    commitment_fr.to_bytes()
}

/// Nullifier generation: Hash(private_key || commitment_index)
pub fn create_nullifier(sk: &[u8], commitment_index: u64) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new();
    hasher.update(sk);
    hasher.update(&commitment_index.to_le_bytes());
    hasher.finalize().into()
}

/// Halo2 Chip Configuration for Value Conservation and Range Proofs
#[derive(Clone, Debug)]
pub struct ValueConfig {
    pub advice: [Column<Advice>; 5], // [amount, blinding, commitment, running_sum, type_indicator]
    pub range_z: Column<Advice>,    // running sum for bit decomposition (replaces 64 bit columns)
    pub instance: Column<Instance>,
    pub selector: Selector,
    pub range_selector: Selector,
    pub first_row_selector: Selector,
}

/// A circuit for verifying value conservation and range proofs.
/// sum(inputs) == sum(outputs) AND all amounts are in [0, 2^64)
#[derive(Default)]
pub struct ValueConservationCircuit {
    input_amounts: Vec<u64>,
    output_amounts: Vec<u64>,
    input_blindings: Vec<[u8; 32]>,
    output_blindings: Vec<[u8; 32]>,
    public_amount: i64,
    commitment_hash: Fr,
}

impl ValueConservationCircuit {
    pub fn dummy() -> Self {
        Self {
            input_amounts: vec![0; MAX_INPUTS],
            output_amounts: vec![0; MAX_OUTPUTS],
            input_blindings: vec![[0u8; 32]; MAX_INPUTS],
            output_blindings: vec![[0u8; 32]; MAX_OUTPUTS],
            public_amount: 0,
            commitment_hash: Fr::zero(),
        }
    }
}

impl Circuit<Fr> for ValueConservationCircuit {
    type Config = ValueConfig;
    type FloorPlanner = SimpleFloorPlanner;

    fn without_witnesses(&self) -> Self {
        Self::dummy()
    }

    fn configure(meta: &mut ConstraintSystem<Fr>) -> Self::Config {
        let advice = [
            meta.advice_column(), 
            meta.advice_column(), 
            meta.advice_column(),
            meta.advice_column(),
            meta.advice_column()
        ];
        let instance = meta.instance_column();
        let selector = meta.selector();
        let range_selector = meta.selector();
        let first_row_selector = meta.selector();

        meta.enable_equality(instance);
        for col in advice.iter() {
            meta.enable_equality(*col);
        }

        let range_z = meta.advice_column();
        meta.enable_equality(range_z);

        meta.create_gate("first row conservation", |meta| {
            let s = meta.query_selector(first_row_selector);
            let amount = meta.query_advice(advice[0], Rotation::cur());
            let running_sum = meta.query_advice(advice[3], Rotation::cur());
            let indicator = meta.query_advice(advice[4], Rotation::cur());

            vec![s * (running_sum - indicator * amount)]
        });

        meta.create_gate("conservation and binding", |meta| {
            let s = meta.query_selector(selector);
            let amount = meta.query_advice(advice[0], Rotation::cur());
            let blinding = meta.query_advice(advice[1], Rotation::cur());
            let commitment = meta.query_advice(advice[2], Rotation::cur());

            let running_sum_cur = meta.query_advice(advice[3], Rotation::cur());
            let running_sum_prev = meta.query_advice(advice[3], Rotation::prev());
            let indicator = meta.query_advice(advice[4], Rotation::cur());

            vec![
                  s.clone() * (amount.clone() + blinding - commitment),
                  s * (running_sum_cur - (running_sum_prev + indicator * amount)),
              ]
        });

        meta.create_gate("range check running sum", |meta| {
            let s = meta.query_selector(range_selector);
            let z_prev = meta.query_advice(range_z, Rotation::prev());
            let z_cur = meta.query_advice(range_z, Rotation::cur());
            // Extract bit: b = z_prev - 2*z_cur
            // Constrain b ∈ {0,1}: b * (1 - b) = 0
            let bit = z_prev - Expression::Constant(Fr::from(2)) * z_cur;
            vec![s * bit.clone() * (Expression::Constant(Fr::one()) - bit)]
        });

        ValueConfig {
            advice,
            range_z,
            instance,
            selector,
            range_selector,
            first_row_selector,
        }
    }

    fn synthesize(&self, config: Self::Config, mut layouter: impl Layouter<Fr>) -> Result<(), ErrorFront> {
        // ── Merged Region: Value Conservation + Running-sum Range Proofs ──
        // Each amount gets 65 contiguous rows: [conservation_row + 64 range_check rows]
        // Conservation row i has amount in advice[0] and range_z (linked via constrain_equal).
        // Range gate at row i+1 checks amt_i - 2*z_1 ∈ {0,1} via Rotation::prev().
        let total_amounts = MAX_INPUTS + MAX_OUTPUTS;
        let two_inv = Fr::from(2).invert().unwrap();

        let (last_sum_cell, range_final_cells): (_, Vec<_>) = layouter.assign_region(
            || "value conservation + range proofs",
            |mut region| {
                let mut row: usize = 0;
                let mut running_sum = Fr::zero();
                let mut last_sum = None;
                let mut final_cells = Vec::with_capacity(total_amounts);

                for i in 0..MAX_INPUTS {
                    let amount = self.input_amounts.get(i).cloned().unwrap_or(0);
                    let amt_fr = Fr::from(amount);

                    // ── Conservation row ──
                    if row == 0 {
                        config.first_row_selector.enable(&mut region, row)?;
                    } else {
                        config.selector.enable(&mut region, row)?;
                    }

                    let mut blinding_bytes = [0u8; 32];
                    if let Some(b) = self.input_blindings.get(i) {
                        blinding_bytes.copy_from_slice(b);
                    }
                    // C3: Must match create_commitment() — hash blinding with blake3 then mask top bits
                    let h = blake3::hash(&blinding_bytes);
                    let mut masked = *h.as_bytes();
                    masked[31] &= 0x2F;
                    let blind_fr = Fr::from_bytes(&masked).expect("masked bytes always valid Fr");

                    running_sum += amt_fr;

                    let amt_cell = region.assign_advice(|| "input amount", config.advice[0], row, || Value::known(amt_fr))?;
                    region.assign_advice(|| "input blinding", config.advice[1], row, || Value::known(blind_fr))?;
                    region.assign_advice(|| "input commitment", config.advice[2], row, || Value::known(amt_fr + blind_fr))?;
                    last_sum = Some(region.assign_advice(|| "running sum", config.advice[3], row, || Value::known(running_sum))?);
                    region.assign_advice(|| "indicator", config.advice[4], row, || Value::known(Fr::one()))?;
                    // C2: Constrain amount == range_z start value
                    let z0_cell = region.assign_advice(|| "range_z start", config.range_z, row, || Value::known(amt_fr))?;
                    region.constrain_equal(amt_cell.cell(), z0_cell.cell())?;

                    // ── 64 range proof rows (z_1..z_64) ──
                    let mut z = amt_fr;
                    for bit_idx in 0..64 {
                        row += 1;
                        let bit = (amount >> bit_idx) & 1;
                        z = (z - Fr::from(u64::from(bit))) * two_inv;
                        config.range_selector.enable(&mut region, row)?;
                        let cell = region.assign_advice(
                            || format!("range z_{}", bit_idx + 1),
                            config.range_z,
                            row,
                            || Value::known(z),
                        )?;
                        if bit_idx == 63 {
                            final_cells.push(cell);
                            let next_indicator = if i + 1 < MAX_INPUTS { Fr::one() } else { -Fr::one() };
                            region.assign_advice(|| "range running sum", config.advice[3], row, || Value::known(running_sum))?;
                            region.assign_advice(|| "range indicator", config.advice[4], row, || Value::known(next_indicator))?;
                        }
                    }
                    row += 1; // past the last range check row
                }

                for i in 0..MAX_OUTPUTS {
                    let amount = self.output_amounts.get(i).cloned().unwrap_or(0);
                    let amt_fr = Fr::from(amount);

                    // ── Conservation row ──
                    config.selector.enable(&mut region, row)?;

                    let mut blinding_bytes = [0u8; 32];
                    if let Some(b) = self.output_blindings.get(i) {
                        blinding_bytes.copy_from_slice(b);
                    }
                    let h = blake3::hash(&blinding_bytes);
                    let mut masked = *h.as_bytes();
                    masked[31] &= 0x2F;
                    let blind_fr = Fr::from_bytes(&masked).expect("masked bytes always valid Fr");

                    running_sum -= amt_fr;

                    let amt_cell = region.assign_advice(|| "output amount", config.advice[0], row, || Value::known(amt_fr))?;
                    region.assign_advice(|| "output blinding", config.advice[1], row, || Value::known(blind_fr))?;
                    region.assign_advice(|| "output commitment", config.advice[2], row, || Value::known(amt_fr + blind_fr))?;
                    last_sum = Some(region.assign_advice(|| "running sum", config.advice[3], row, || Value::known(running_sum))?);
                    region.assign_advice(|| "indicator", config.advice[4], row, || Value::known(-Fr::one()))?;
                    let z0_cell = region.assign_advice(|| "range_z start", config.range_z, row, || Value::known(amt_fr))?;
                    region.constrain_equal(amt_cell.cell(), z0_cell.cell())?;

                    // ── 64 range proof rows (z_1..z_64) ──
                    let mut z = amt_fr;
                    for bit_idx in 0..64 {
                        row += 1;
                        let bit = (amount >> bit_idx) & 1;
                        z = (z - Fr::from(u64::from(bit))) * two_inv;
                        config.range_selector.enable(&mut region, row)?;
                        let cell = region.assign_advice(
                            || format!("range z_{}", bit_idx + 1),
                            config.range_z,
                            row,
                            || Value::known(z),
                        )?;
                        if bit_idx == 63 {
                            final_cells.push(cell);
                            region.assign_advice(|| "range running sum out", config.advice[3], row, || Value::known(running_sum))?;
                            region.assign_advice(|| "range indicator out", config.advice[4], row, || Value::known(-Fr::one()))?;
                        }
                    }
                    row += 1;
                }

                Ok((last_sum, final_cells))
            },
        )?;

        if let Some(cell) = last_sum_cell {
            layouter.constrain_instance(cell.cell(), config.instance, 0)?;
        }

        let comm_cell = layouter.assign_region(|| "commitment hash", |mut region| {
            region.assign_advice(
                || "comm_hash",
                config.advice[0],
                0,
                || Value::known(self.commitment_hash),
            )
        })?;
        layouter.constrain_instance(comm_cell.cell(), config.instance, 1)?;

        for (i, cell) in range_final_cells.into_iter().enumerate() {
            layouter.constrain_instance(cell.cell(), config.instance, 2 + i)?;
        }

        Ok(())
    }
}

pub fn build_merkle_root(leaves: &[[u8; 32]]) -> [u8; 32] {
    if leaves.is_empty() {
        return blake3::hash(b"empty_tx_list").into();
    }
    let mut layer: Vec<[u8; 32]> = leaves.to_vec();
    while layer.len() > 1 {
        let mut next = Vec::with_capacity((layer.len() + 1) / 2);
        for chunk in layer.chunks(2) {
            let mut h = blake3::Hasher::new();
            h.update(&chunk[0]);
            if chunk.len() > 1 {
                h.update(&chunk[1]);
            } else {
                h.update(&chunk[0]);
            }
            next.push(h.finalize().into());
        }
        layer = next;
    }
    layer[0]
}

pub struct ZKProofSystem;

/// Hash output commitments into a Fr public instance to bind them to the proof.
fn hash_commitments(commitments: &[[u8; 32]]) -> Fr {
    let mut hasher = blake3::Hasher::new();
    for comm in commitments.iter() {
        hasher.update(comm);
    }
    let h = hasher.finalize();
    let mut bytes = *h.as_bytes();
    bytes[31] &= 0x2F;
    Fr::from_bytes(&bytes).expect("masked blake3 output always a valid Fr")
}

impl ZKProofSystem {
    /// Set up KZG parameters (Common Reference String)
    /// In production, this would be generated via a MPC ceremony.
    pub fn setup_params(k: u32) -> ParamsKZG<Bn256> {
        let seed = *b"Aetheris ZK CRS deterministic v1";
        ParamsKZG::<Bn256>::setup(k, &mut ChaCha20Rng::from_seed(seed))
    }

    /// Generates a production-grade KZG proof using globally cached CRS & keys.
    /// Binds output commitments as public instance via `commitment_hash`.
    pub fn prove_conservation(
        in_amounts: &[u64], 
        out_amounts: &[u64],
        in_blindings: &[[u8; 32]],
        out_blindings: &[[u8; 32]],
        commitments: &[[u8; 32]],
        public_amount: i64,
    ) -> Vec<u8> {
        let comm_hash_fr = hash_commitments(&commitments);

        let circuit = ValueConservationCircuit {
            input_amounts: in_amounts.to_vec(),
            output_amounts: out_amounts.to_vec(),
            input_blindings: in_blindings.to_vec(),
            output_blindings: out_blindings.to_vec(),
            public_amount,
            commitment_hash: comm_hash_fr,
        };

        let params = ensure_params();
        let (_, pk) = ensure_keys();

        let pub_amt_fr = if public_amount >= 0 {
            Fr::from(public_amount as u64)
        } else {
            -Fr::from(public_amount.unsigned_abs())
        };

        let mut instance_values = vec![-pub_amt_fr, comm_hash_fr];
        instance_values.resize(2 + MAX_INPUTS + MAX_OUTPUTS, Fr::zero());
        let instances = vec![instance_values];

        let mut transcript = Blake2bWrite::<_, G1Affine, Challenge255<_>>::init(vec![]);
        let mut rng = CryptoRng;

        create_proof::<KZGCommitmentScheme<Bn256>, ProverSHPLONK<'_, Bn256>, _, _, _, _>(
            params,
            pk,
            &[circuit],
            &[instances],
            &mut rng,
            &mut transcript,
        ).expect("proof generation should not fail");

        let proof = transcript.finalize();
        
        let mut final_proof = b"halo2_kzg_v1_".to_vec();
        final_proof.extend_from_slice(&proof);
        final_proof
    }

    /// Verifies a production-grade KZG proof using globally cached CRS & keys.
    /// The proof is bound to the output commitments via `commitments` public instance.
    pub fn verify_conservation(proof_bytes: &[u8], commitments: &[[u8; 32]], public_amount: i64) -> bool {
        if !proof_bytes.starts_with(b"halo2_kzg_v1_") {
            return false;
        }

        let comm_hash_fr = hash_commitments(&commitments);

        let params = ensure_params();
        let (vk, _) = ensure_keys();

        let pub_amt_fr = if public_amount >= 0 {
            Fr::from(public_amount as u64)
        } else {
            -Fr::from(public_amount.unsigned_abs())
        };

        let mut instance_values = vec![-pub_amt_fr, comm_hash_fr];
        instance_values.resize(2 + MAX_INPUTS + MAX_OUTPUTS, Fr::zero());
        let instances = vec![instance_values];

        let mut transcript = Blake2bRead::<_, G1Affine, Challenge255<_>>::init(&proof_bytes[b"halo2_kzg_v1_".len()..]);
        
        let verifier_params = params.verifier_params();
        let instances_vec: Vec<Vec<Fr>> = instances;
        
        verify_proof::<KZGCommitmentScheme<Bn256>, VerifierSHPLONK<Bn256>, Challenge255<G1Affine>, _, SingleStrategy<Bn256>>(
            &verifier_params,
            vk,
            &[instances_vec],
            &mut transcript,
        )
    }

    /// Aggregate multiple transaction proofs into a single authenticated commitment
    /// using a Merkle tree over tx proofs, bound with the previous block proof,
    /// block height, and state root.
    /// Each tx must supply its output commitments for individual proof verification.
    pub fn aggregate_proofs(
        last_block_proof: &[u8],
        tx_proofs: &[Vec<u8>],
        tx_commitments: &[Vec<[u8; 32]>],
        public_amounts: &[i64],
        height: u64,
        state_root: &[u8; 32],
    ) -> Result<Vec<u8>, String> {
        if tx_proofs.len() != public_amounts.len() || tx_proofs.len() != tx_commitments.len() {
            return Err("Proof count mismatch".to_string());
        }
        for (i, (tx_proof, comms)) in tx_proofs.iter().zip(tx_commitments.iter()).enumerate() {
            if !Self::verify_conservation(tx_proof, comms, public_amounts[i]) {
                return Err(format!("Invalid transaction proof at index {} for block {}", i, height));
            }
        }

        let leaves: Vec<[u8; 32]> = tx_proofs.iter().map(|p| {
            let mut h = blake3::Hasher::new();
            h.update(p);
            h.finalize().into()
        }).collect();

        let merkle_root = build_merkle_root(&leaves);

        let mut hasher = blake3::Hasher::new();
        if height > 0 {
            hasher.update(last_block_proof);
        } else {
            hasher.update(b"AETHERIS_GENESIS_ROOT");
        }
        hasher.update(&merkle_root);
        hasher.update(&height.to_le_bytes());
        hasher.update(state_root);

        let hash = hasher.finalize();
        let mut final_proof = b"aetheris_aggregate_v1_".to_vec();
        final_proof.extend_from_slice(hash.as_bytes());
        final_proof.extend_from_slice(&merkle_root);
        final_proof.extend_from_slice(&(leaves.len() as u64).to_le_bytes());

        println!("[AGGREGATE] Bound {} tx proofs into aggregate at height {}", tx_proofs.len(), height);
        Ok(final_proof)
    }

    /// Verify an aggregate proof by recomputing the Merkle root from provided
    /// tx proofs and checking the binding hash chain.
    /// Each tx must supply its output commitments for individual proof verification.
    pub fn verify_aggregate(
        aggregate_proof: &[u8],
        prev_block_proof: &[u8],
        tx_proofs: &[Vec<u8>],
        tx_commitments: &[Vec<[u8; 32]>],
        public_amounts: &[i64],
        height: u64,
        state_root: &[u8; 32]
    ) -> bool {
        if !aggregate_proof.starts_with(b"aetheris_aggregate_v1_") {
            return false;
        }
        if aggregate_proof.len() < 22 + 32 + 32 + 8 {
            return false;
        }

        let stored_merkle_root = &aggregate_proof[22 + 32..22 + 32 + 32];

        if tx_proofs.len() != public_amounts.len() || tx_proofs.len() != tx_commitments.len() {
            return false;
        }
        for (i, proof) in tx_proofs.iter().enumerate() {
            if !Self::verify_conservation(proof, &tx_commitments[i], public_amounts[i]) {
                return false;
            }
        }

        let leaves: Vec<[u8; 32]> = tx_proofs.iter().map(|p| {
            let mut h = blake3::Hasher::new();
            h.update(p);
            h.finalize().into()
        }).collect();
        let computed_root = build_merkle_root(&leaves);
        if &computed_root != stored_merkle_root {
            return false;
        }

        let mut hasher = blake3::Hasher::new();
        if height > 0 {
            hasher.update(prev_block_proof);
        } else {
            hasher.update(b"AETHERIS_GENESIS_ROOT");
        }
        hasher.update(stored_merkle_root);
        hasher.update(&height.to_le_bytes());
        hasher.update(state_root);

        let expected = hasher.finalize();
        &aggregate_proof[22..22 + 32] == expected.as_bytes()
    }

    /// Encrypts a transaction output for a specific recipient using proper DH key exchange.
    pub fn encrypt_output(
        viewing_key: &[u8; 32],
        amount: u64,
        blinding: &[u8; 32],
    ) -> ([u8; 32], Vec<u8>) {
        // Proper DH key exchange using x25519-dalek:
        // 1. Generate ephemeral x25519 key pair
        // 2. DH(ephemeral_sk, recipient_pk) → shared_secret
        // 3. Derive encryption key from shared_secret
        
        let ephem_secret = EphemeralSecret::random_from_rng(CryptoRng);
        let ephem_public = PublicKey::from(&ephem_secret);
        
        // Derive recipient's public key from their viewing key (treated as secret key)
        let recipient_secret = StaticSecret::from(*viewing_key);
        let recipient_public = PublicKey::from(&recipient_secret);
        
        // DH with recipient's public key
        let shared_secret = ephem_secret.diffie_hellman(&recipient_public);
        
        // Derive encryption key from shared secret
        let enc_key = blake3::hash(shared_secret.as_bytes());
        let key = Key::<Aes256Gcm>::from_slice(enc_key.as_bytes());
        let cipher = Aes256Gcm::new(key);
        let nonce = Aes256Gcm::generate_nonce(&mut CryptoRng);
        
        let mut payload = amount.to_le_bytes().to_vec();
        payload.extend_from_slice(blinding);
        
        let ciphertext = cipher.encrypt(&nonce, payload.as_slice()).expect("Note encryption failed");
        let mut result = nonce.to_vec();
        result.extend_from_slice(&ciphertext);
        
        (ephem_public.to_bytes(), result)
    }

    /// Encrypts a transaction note for a specific recipient.
    /// NOTE: viewing_key is treated as the secret key for DH shared secret derivation.
    pub fn encrypt_note(
        viewing_key: &[u8; 32],
        ephemeral_pk: &[u8; 32],
        amount: u64,
        blinding: &[u8; 32],
    ) -> Vec<u8> {
        // Proper DH: shared_secret = DH(viewing_sk, epk)
        let viewing_secret = StaticSecret::from(*viewing_key);
        let epk = PublicKey::from(*ephemeral_pk);
        let shared_secret = viewing_secret.diffie_hellman(&epk);
        let enc_key = blake3::hash(shared_secret.as_bytes());
        
        let key = Key::<Aes256Gcm>::from_slice(enc_key.as_bytes());
        let cipher = Aes256Gcm::new(key);
        let nonce = Aes256Gcm::generate_nonce(&mut CryptoRng);
        
        let mut payload = amount.to_le_bytes().to_vec();
        payload.extend_from_slice(blinding);
        
        let ciphertext = cipher.encrypt(&nonce, payload.as_slice()).expect("Note encryption failed");
        let mut result = nonce.to_vec();
        result.extend_from_slice(&ciphertext);
        result
    }

    /// Trial decryption to scan for owned records using proper DH shared secret.
    pub fn trial_decrypt(
        viewing_key: &[u8; 32],
        ephemeral_pk: &[u8; 32],
        ciphertext: &[u8],
    ) -> Option<(u64, [u8; 32])> {
        // Proper DH: shared_secret = DH(viewing_sk, epk)
        if ciphertext.len() < 12 { return None; }
        let nonce = Nonce::from_slice(&ciphertext[..12]);
        let encrypted = &ciphertext[12..];

        let viewing_secret = StaticSecret::from(*viewing_key);
        let epk = PublicKey::from(*ephemeral_pk);
        let shared_secret = viewing_secret.diffie_hellman(&epk);
        let enc_key = blake3::hash(shared_secret.as_bytes());

        let key = Key::<Aes256Gcm>::from_slice(enc_key.as_bytes());
        let cipher = Aes256Gcm::new(key);

        let decrypted = cipher.decrypt(nonce, encrypted).ok()?;
        if decrypted.len() != 40 { return None; }

        let amount = u64::from_le_bytes(decrypted[0..8].try_into().ok()?);
        let mut blinding = [0u8; 32];
        blinding.copy_from_slice(&decrypted[8..40]);
        
        Some((amount, blinding))
    }

    /// Proves a VDF computation for inclusion in a BlockHeader
    pub fn prove_vdf(seed: &[u8], result: &[u8], difficulty: u64) -> Vec<u8> {
        let mut hasher = blake3::Hasher::new();
        hasher.update(seed);
        hasher.update(result);
        hasher.update(&difficulty.to_le_bytes());
        let hash = hasher.finalize();
        
        let mut proof = b"vdf_zkp_v2_".to_vec();
        proof.extend_from_slice(hash.as_bytes());
        proof
    }
}


#[cfg(test)]
mod tests {
    use super::*;

    fn make_proof(in_amounts: &[u64], out_amounts: &[u64], public_amount: i64) -> Vec<u8> {
        let in_blindings: Vec<[u8; 32]> = (0..in_amounts.len())
            .map(|i| [i as u8; 32]).collect();
        let out_blindings: Vec<[u8; 32]> = (0..out_amounts.len())
            .map(|i| [(in_amounts.len() + i) as u8; 32]).collect();
        ZKProofSystem::prove_conservation(
            in_amounts, out_amounts, &in_blindings, &out_blindings, &[], public_amount,
        )
    }

    fn random_key() -> [u8; 32] {
        let mut key = [0u8; 32];
        CryptoRng.fill_bytes(&mut key);
        key
    }

    #[test]
    fn test_kzg_prove_verify_roundtrip() {
        let proof = make_proof(&[100, 50], &[150], 0);
        assert!(ZKProofSystem::verify_conservation(&proof, &[], 0));
        println!("[TEST 1] KZG prove + verify round-trip: OK");
    }

    #[test]
    fn test_invalid_proof_rejection() {
        let proof = make_proof(&[100], &[100], 0);
        assert!(!ZKProofSystem::verify_conservation(&proof, &[], 1));
        println!("[TEST 2] Invalid proof rejection: OK");
    }

    #[test]
    fn test_empty_value() {
        let proof = make_proof(&[], &[], 0);
        assert!(ZKProofSystem::verify_conservation(&proof, &[], 0));
        println!("[TEST 3] Empty value proof: OK");
    }

    #[test]
    fn test_large_value() {
        let proof = make_proof(&[u64::MAX, 1], &[u64::MAX], -1);
        assert!(ZKProofSystem::verify_conservation(&proof, &[], -1));
        println!("[TEST 4] Large value (u64::MAX) proof: OK");
    }

    #[test]
    fn test_encryption_roundtrip() {
        let vk = random_key();
        let epk = random_key();
        let blinding = random_key();
        let ciphertext = ZKProofSystem::encrypt_note(&vk, &epk, 12345, &blinding);
        let decrypted = ZKProofSystem::trial_decrypt(&vk, &epk, &ciphertext);
        assert!(decrypted.is_some());
        assert_eq!(decrypted.unwrap(), (12345, blinding));
        println!("[TEST 5] Encryption round-trip: OK");
    }

    #[test]
    fn test_encryption_wrong_key() {
        let vk1 = random_key();
        let vk2 = random_key();
        let epk = random_key();
        let blinding = random_key();
        let ciphertext = ZKProofSystem::encrypt_note(&vk1, &epk, 42, &blinding);
        let decrypted = ZKProofSystem::trial_decrypt(&vk2, &epk, &ciphertext);
        assert!(decrypted.is_none());
        println!("[TEST 6] Wrong key rejection: OK");
    }

    #[test]
    fn test_tampered_ciphertext() {
        let vk = random_key();
        let epk = random_key();
        let blinding = random_key();
        let mut ciphertext = ZKProofSystem::encrypt_note(&vk, &epk, 999, &blinding);
        if ciphertext.len() > 13 {
            ciphertext[13] ^= 0xFF;
        }
        let decrypted = ZKProofSystem::trial_decrypt(&vk, &epk, &ciphertext);
        assert!(decrypted.is_none());
        println!("[TEST 7] Tampered ciphertext rejection: OK");
    }

    #[test]
    fn test_special_chars() {
        let mut hasher = blake3::Hasher::new();
        hasher.update("🚀🌕💰你好 αβγ".as_bytes());
        let hash = hasher.finalize();
        let amount = u64::from_le_bytes(hash.as_bytes()[..8].try_into().unwrap());
        let proof = make_proof(&[amount], &[amount], 0);
        assert!(ZKProofSystem::verify_conservation(&proof, &[], 0));

        let vk = random_key();
        let epk = random_key();
        let mut blinding = [0u8; 32];
        blinding.copy_from_slice(hash.as_bytes());
        let ciphertext = ZKProofSystem::encrypt_note(&vk, &epk, amount, &blinding);
        let decrypted = ZKProofSystem::trial_decrypt(&vk, &epk, &ciphertext);
        assert!(decrypted.is_some());
        assert_eq!(decrypted.unwrap(), (amount, blinding));
        println!("[TEST 8] Special chars round-trip: OK");
    }

    #[test]
    fn test_nonce_uniqueness() {
        let vk = random_key();
        let epk = random_key();
        let blinding = random_key();
        let ct1 = ZKProofSystem::encrypt_note(&vk, &epk, 42, &blinding);
        let ct2 = ZKProofSystem::encrypt_note(&vk, &epk, 42, &blinding);
        assert_ne!(ct1, ct2, "ciphertexts should differ");
        assert_ne!(&ct1[..12], &ct2[..12], "nonces should differ");
        println!("[TEST 9] Nonce uniqueness: OK");
    }

    #[test]
    fn test_multiple_proofs() {
        let cases = [
            (&[10u64, 20] as &[u64], &[30u64] as &[u64], 0i64),
            (&[100], &[100], 0),
            (&[1, 2, 3], &[6], 0),
            (&[u64::MAX], &[u64::MAX], 0),
            (&[5, 5, 5], &[10, 5], 0),
        ];
        for (i, (ins, outs, pub_amt)) in cases.iter().enumerate() {
            let proof = make_proof(ins, outs, *pub_amt);
            assert!(
                ZKProofSystem::verify_conservation(&proof, &[], *pub_amt),
                "proof {} should verify", i
            );
            println!("[TEST 10] Proof {} verified", i);
        }
        println!("[TEST 10] Multiple proof round-trips: OK");
    }

    #[test]
    fn test_aggregate_empty_roundtrip() {
        let prev_proof = b"aetheris_aggregate_v1_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_vec();
        let agg = ZKProofSystem::aggregate_proofs(&prev_proof, &[], &[], &[], 1, &[0u8; 32]).unwrap();
        assert!(ZKProofSystem::verify_aggregate(&agg, &prev_proof, &[], &[], &[], 1, &[0u8; 32]),
            "empty aggregate roundtrip should verify");
        println!("[TEST AGG] Empty aggregate roundtrip: OK (len={})", agg.len());
    }

    #[test]
    fn test_aggregate_commitment_binding() {
        // S-3 regression: aggregate proof must bind output commitments.
        // generate a proof with real commitments
        let ins = [10u64, 20];
        let outs = [30u64];
        let in_blindings = vec![[1u8; 32], [2u8; 32]];
        let out_blindings = vec![[3u8; 32]];
        let commitments = vec![
            create_commitment(30, &[3u8; 32]), // commitment matching the output
        ];
        let proof = ZKProofSystem::prove_conservation(&ins, &outs, &in_blindings, &out_blindings, &commitments, 0);

        // Verification with correct commitments must pass
        assert!(ZKProofSystem::verify_conservation(&proof, &commitments, 0),
            "honest verification must pass");

        // Verification with different commitments must fail
        let wrong_commitments = vec![[0xADu8; 32]];
        assert!(!ZKProofSystem::verify_conservation(&proof, &wrong_commitments, 0),
            "commitment binding: wrong commitments must fail verification");

        // Aggregate path: correct tx_commitments passes, wrong ones fail
        let prev = b"aetheris_aggregate_v1_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_vec();
        let agg = ZKProofSystem::aggregate_proofs(
            &prev, &[proof.clone()], &[commitments.clone()], &[0], 1, &[0u8; 32]
        ).expect("aggregate with correct commitments");

        assert!(ZKProofSystem::verify_aggregate(
            &agg, &prev, &[proof.clone()], &[commitments.clone()], &[0], 1, &[0u8; 32]
        ), "aggregate with correct commitments must verify");

        assert!(!ZKProofSystem::verify_aggregate(
            &agg, &prev, &[proof.clone()], &[wrong_commitments], &[0], 1, &[0u8; 32]
        ), "aggregate with wrong commitments must fail");

        println!("[TEST AGG] Commitment binding (S-3): OK");
    }

    #[test]
    fn test_crs_loaded_from_file() {
        // S-4 regression: ensure_params() must load crs.bin from file
        // when the file exists in the working directory
        let params = ensure_params();
        assert_eq!(params.k(), 11, "CRS must have k=11");
        assert!(params.n() > 0, "CRS params n must be positive");
        // Verify the params produce valid keys (ensures VK/PK are consistent with CRS)
        let (_vk, _pk) = ensure_keys();
        println!("[TEST CRS] CRS file loading (S-4): OK (k={}, n={})", params.k(), params.n());
    }

    #[test]
    fn test_proof_tamper_detection() {
        // Additional security: a tampered proof must be rejected
        let ins = [5u64];
        let outs = [5u64];
        let bl = [[7u8; 32]];
        let cm = [create_commitment(5, &[7u8; 32])];
        let proof = ZKProofSystem::prove_conservation(&ins, &outs, &bl, &bl, &cm, 0);

        // Flip one byte in the proof body
        let mut tampered = proof.clone();
        let body_start = b"halo2_kzg_v1_".len();
        if tampered.len() > body_start + 1 {
            tampered[body_start] ^= 0xFF;
        }
        assert!(!ZKProofSystem::verify_conservation(&tampered, &cm, 0),
            "tampered proof must be rejected");
        println!("[TEST TAMPER] Proof tamper detection: OK");
    }
}
